### ISSUE TITLE
Plugin non activé après installation

### ISSUE THREAD

**Issue by cbruno1** [sveyret/pluma-grammalecte#8]
Bonjour,

Tout d’abord  les informations concernant mon système :

OS : Ubuntu 20.04.1 LTS
Version de Python : 3.8.2
Version de Pluma : 1.24.0
Version de Grammalecte CLI/Server : v1.12.2
Version du plugin : 0.4

Après avoir installé la version CLI de Grammalecte et le plugin pour Pluma, grammalect n’apparait pas dans le menu.

![Capture d’écran_2020-09-20_14-14-51](https://user-images.githubusercontent.com/67806509/93711222-c508dc80-fb4c-11ea-9c36-c44c4ca09a6d.png)

Cependant les suggestions d'orthographes fonctionnent via le menu contextuel :

![Capture d’écran_2020-09-20_14-25-57](https://user-images.githubusercontent.com/67806509/93711280-43fe1500-fb4d-11ea-9c0f-35b0357470bc.png)

Sauf erreur de ma part, il me semble qu’une infobulle doit apparaitre lorsque le curseur est sur le mot à corriger.

L'extension est installée dans le répertoire suivant :
```
$ locate pluma-plugin
/usr/lib/pluma/plugins/grammalecte.pluma-plugin
/usr/share/pluma/icons/pluma-plugin.png
```
En revanche impossible de trouver le fichier de configuration :

`$ locate grammalecte.conf`

As-tu une idée de la source du problème ?

Merci d’avance.

**Comment by sveyret** [comment]
Bonjour,
Je n'ai pas touché à ce greffon depuis de nombreuses années et n'utilise plus _Pluma_ aujourd'hui. Je vais donc être bien embêté pour t'aider.
Je pense qu'il doit y avoir une manipulation à faire pour activer le greffon, puisqu'il y a un incident d'ouvert pour cela, mais je ne m'en souviens plus.
Je te conseille de vérifier avec le mode d'emploi si tu as bien effectué correctement l'installation. Peut-être est-il nécessaire de créer le fichier de configuration…

**Comment by cbruno1** [comment]
Merci pour la réponse rapide,

> Je pense qu’il doit y avoir une manipulation à faire pour activer le greffon, puisqu’il y a un incident d’ouvert pour cela, mais je ne m’en souviens plus.

Tu parles de [celui-ci](https://github.com/sveyret/pluma-grammalecte/issues/7) ?

> Je te conseille de vérifier avec le mode d'emploi si tu as bien effectué correctement l'installation. Peut-être est-il nécessaire de créer le fichier de configuration…

Je l'ai lu et relu plusieurs fois, mais cela ne suffit pas.
Je viens de créer le fichier de configuration en y insérant le chemin du "binaire" grammalecte-cli.

`{ "g-cli": "/usr/local/bin/grammalecte-cli.py" }`

Est-ce la bonne manipulation ?

Malheureusement cela n'a rien changé.

**Comment by sveyret** [comment]
> Tu parles de [celui-ci](https://github.com/sveyret/pluma-grammalecte/issues/7) ?

Oui, c'est bien celui là.

> `{ "g-cli": "/usr/local/bin/grammalecte-cli.py" }`
> 
> Est-ce la bonne manipulation ?

En effet, cette option est nécessaire, puisque l'emplacement par défaut est `/opt/grammalecte/cli.py`. Peut-être y a-t-il besoin également de `locale-dir` ?

Mais ce qui m'inquiète le plus, c'est que depuis tout ce temps, il est bien possible que le greffon ne soit plus compatible avec les nouvelles versions de _Pluma_. D'autant qu'actuellement, _Python 2_ est en train d'être retiré de tous les projets libre, devenant obsolète, au profit de _Python 3_. Or, le greffon fonctionne en _Python 2_…

**Comment by cbruno1** [comment]
> En effet, cette option est nécessaire, puisque l'emplacement par défaut est /opt/grammalecte/cli.py. Peut-être y a-t-il besoin également de locale-dir ?

J'ai ajouté le répertoire d'installation :

`{ "locale-dir": "/usr/local/bin", "g-cli": "/usr/local/bin/grammalecte-cli.py" }`

Toujours rien de probant. J'ai également vérifié si Python 2 été installé, c'est bien le cas.

Merci pour l'aide en tout cas !

**Comment by sveyret** [comment]
Tu es sûr de ton coup pour le répertoire des traductions ? Cela me semble plutôt être un répertoire de binaires…

> J'ai également vérifié si Python 2 été installé

Oui, mais il faut également que _Pluma_ accepte encore cette version de _Python_.

**Comment by cbruno1** [comment]
> Tu es sûr de ton coup pour le répertoire des traductions ? Cela me semble plutôt être un répertoire de binaires…

Du coup non, je n'ai pas trouvé ce répertoire car je ne sais pas quoi chercher.

> Oui, mais il faut également que Pluma accepte encore cette version de Python.

Je vois !
